# Generated by Django 5.0 on 2024-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermodel",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("7 класс", 7),
                    ("8 класс", 8),
                    ("9 класс", 9),
                    ("10 класс", 10),
                    ("11 класс", 11),
                    ("1 курс ", 1),
                    ("2 курс", 2),
                    ("3 курс", 4),
                    ("4 курс", 4),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
