# Generated by Django 5.0 on 2024-02-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_membermodel_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermodel",
            name="languages",
            field=models.TextField(default="Русский - родной", null=True),
        ),
        migrations.AlterField(
            model_name="membermodel",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("7 класс", "7 класс"),
                    ("8 класс", "8 класс"),
                    ("9 класс", "9 класс"),
                    ("10 класс", "10 класс"),
                    ("11 класс", "11 класс"),
                    ("1 курс ", "1 курс"),
                    ("2 курс", "2 курс"),
                    ("3 курс", "3 курс"),
                    ("4 курс", "4 курс"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
